[2024-07-24T04:02:40.081+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-24T04:02:40.105+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: MyTest.export_xlsx manual__2024-07-24T04:02:36.214113+00:00 [queued]>
[2024-07-24T04:02:40.114+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: MyTest.export_xlsx manual__2024-07-24T04:02:36.214113+00:00 [queued]>
[2024-07-24T04:02:40.114+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-24T04:02:40.130+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): export_xlsx> on 2024-07-24 04:02:36.214113+00:00
[2024-07-24T04:02:40.138+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=1416) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-24T04:02:40.139+0000] {standard_task_runner.py:64} INFO - Started process 1419 to run task
[2024-07-24T04:02:40.139+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'MyTest', 'export_xlsx', 'manual__2024-07-24T04:02:36.214113+00:00', '--job-id', '73', '--raw', '--subdir', 'DAGS_FOLDER/MyTest.py', '--cfg-path', '/tmp/tmpva01vc7o']
[2024-07-24T04:02:40.140+0000] {standard_task_runner.py:91} INFO - Job 73: Subtask export_xlsx
[2024-07-24T04:02:40.180+0000] {task_command.py:426} INFO - Running <TaskInstance: MyTest.export_xlsx manual__2024-07-24T04:02:36.214113+00:00 [running]> on host ed4de24231fa
[2024-07-24T04:02:40.271+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='MyTest' AIRFLOW_CTX_DAG_ID='MyTest' AIRFLOW_CTX_TASK_ID='export_xlsx' AIRFLOW_CTX_EXECUTION_DATE='2024-07-24T04:02:36.214113+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-24T04:02:36.214113+00:00'
[2024-07-24T04:02:40.272+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-24T04:02:40.272+0000] {logging_mixin.py:188} INFO - <class 'str'>
[2024-07-24T04:02:40.275+0000] {warnings.py:112} WARNING - /opt/***/dags/MyTest.py:110: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_json(df_json)  # Deserialize the JSON string back to a DataFrame

[2024-07-24T04:02:40.288+0000] {logging_mixin.py:188} INFO - <class 'pandas.core.frame.DataFrame'>
[2024-07-24T04:02:40.289+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-24T04:02:40.290+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/MyTest.py", line 118, in export_xlsx_func
    body += df
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/ops/common.py", line 76, in new_method
    return method(self, other)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/arraylike.py", line 190, in __radd__
    return self._arith_method(other, roperator.radd)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 7644, in _arith_method
    new_data = self._dispatch_frame_op(other, op, axis=axis)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 7676, in _dispatch_frame_op
    bm = self._mgr.apply(array_op, right=right)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/internals/managers.py", line 352, in apply
    applied = b.apply(f, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/internals/blocks.py", line 366, in apply
    result = func(self.values, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/ops/array_ops.py", line 285, in arithmetic_op
    res_values = _na_arithmetic_op(left, right, op)  # type: ignore[arg-type]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/ops/array_ops.py", line 220, in _na_arithmetic_op
    result = func(left, right)
             ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/roperator.py", line 11, in radd
    return right + left
           ~~~~~~^~~~~~
numpy.core._exceptions._UFuncNoLoopError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U57'), dtype('int64')) -> None
[2024-07-24T04:02:40.304+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=MyTest, task_id=export_xlsx, run_id=manual__2024-07-24T04:02:36.214113+00:00, execution_date=20240724T040236, start_date=20240724T040240, end_date=20240724T040240
[2024-07-24T04:02:40.315+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 73 for task export_xlsx (ufunc 'add' did not contain a loop with signature matching types (dtype('<U57'), dtype('int64')) -> None; 1419)
[2024-07-24T04:02:40.353+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-24T04:02:40.371+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-24T04:02:40.373+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
